src/answer/urls.py
from django.urls import path
from . import views


app_name = 'answer'
urlpatterns = [
    path('start/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/questions/urls.py
from django.urls import path

from . import views
app_name = 'quest'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user_register.views import *
from rest_framework import routers
from question.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_register.urls')),
    path('login/', include('answer.urls'), name='st'),
]

if settings.DEBUG:
    urlpatterns = [
                    path('__debug__/', include('debug_toolbar.urls')),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_register/urls.py
from django.urls import path, include
from .views import *
from question.views import *
from rest_framework import routers
from question.views import *


urlpatterns = [
    #страница регистрации пользователя
    path('', HomePage.as_view(), name='home'),

    path('register/', register, name='register'),
    path('login/', User_login, name='login'),
    path('logout/', User_logout, name='logout'),
    path('question/', GetQuestion.as_view(), name='question'),
    path('answer/', QuestionAnswer.as_view(), name='answer'),


]

src/answer/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    # Подключения времени к модели

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/question/models.py
from django.conf import settings
from django.db import models


#Модель вопросов
class Question(models.Model):
    title = models.CharField(max_length=4096)
    visible = models.BooleanField(default=False)
    max_points = models.FloatField()

    def __str__(self):
           return self.title


#Модель выбора
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    points = models.FloatField()
    lock_other = models.BooleanField(default=False)

    def __str__(self):
        return self.title


# Связующая модель вопрос/ответ
class Answer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.choice.title

src/user_register/models.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User


#Форма логина пользователя
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
#Форма регистрации пользователя
class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='e-mail:', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', help_text='Пиши нормальный пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Потверждение пароля', help_text='Повтори без ошибок', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

src/answer/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from answer.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'answer/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'answer/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'answer/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'answer/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('answer:results', args=(question.id,)))

    def results(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'answer/results.html', {'question': question})

src/question/views.py
from .serializers import QuestionSerializer, AnswerSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.generics import GenericAPIView, CreateAPIView, ListAPIView
from rest_framework.response import Response
from .models import Question

class GetQuestion(ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = QuestionSerializer
    queryset = Question.objects.filter(visible=True).all()

class QuestionAnswer(CreateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = AnswerSerializer

src/user_register/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from django.views.generic import TemplateView

from user_register.models import UserRegisterForm, UserLoginForm


class HomePage(TemplateView):
    template_name = 'user_register/base.html'

# Регистрации пользователя и в случае успеха переход на страницу с вопросами
def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегистрировались')
            return render(request, 'answer/index.html', {"form": form})
        else:
            for message in form.error_messages:
                messages.error(request, message)
    else:
        form = UserRegisterForm()
    return render(request, 'user_register/register.html', {"form": form})

# Авторизация пользователя и в случае успеха переход на страницу с вопросами
def User_login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('start/')

    else:
        form = UserLoginForm()
    return render(request, 'user_register/login.html', {"form": form})

# При выходе отправляемся на home page
def User_logout(request):
    logout(request)
    return redirect('home')

src/answer/templates/answer/detail.html
<form action="{% url 'answer:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

src/answer/templates/answer/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'answer/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
{#        <li><a href="/answer/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>#}
        <li><a href="{% url 'answer:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

src/answer/templates/answer/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'answer:detail' question.id %}">Vote again?</a>

src/user_register/templates/user_register/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'register' %}">Register</a>
    <a class="navbar-brand" href="{% url 'login' %}">Login</a>
    <a class="navbar-brand" href="{% url 'register' %}">logout</a>
  </div>
 </nav>

src/user_register/templates/user_register/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}News of world{% endblock %}</title>
</head>
<body>

{% include 'user_register/_nav.html' %}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            {% block sidebar %}SIDERBAR{% endblock %}
        </div>
    </div>
</div>

{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</body>

src/user_register/templates/user_register/index.html
{% load static %}

{% extends "user_register/base.html" %}
{% block sidebar %}
{% endblock %}

src/user_register/templates/user_register/login.html
{% extends "user_register/base.html" %}


{% block title %}
login :: {{ block.super }}
{% endblock %}


{% block content %}
<h1>Login</h1>
    <!--форма-->
<form method="post">
    {% csrf_token %} <!--Без этого тега данные не будут сохраняться на сервер и проверяться-->
    {{ form.as_p }} <!-- Элименты формы будит в пораграфе -->
    <button type="submit" class="btn btn-primary btn-block">Login</button>
</form>


{% endblock %}

src/user_register/templates/user_register/register.html
{% extends "user_register/base.html" %}

{% block title %}
Регистрация :: {{ block.super }}
{% endblock %}


{% block content %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %} <!--Без этого тега данные не будут сохраняться на сервер и проверяться-->
    {{ form.as_p }} <!-- Элименты формы будит в пораграфе -->
    <button type="submit" class="btn btn-primary btn-block">Регистрация</button>
</form>


{% endblock %}